### ISSUE TITLE
добавить поддержку mix графиков

### ISSUE THREAD

**Issue by AntonS86** [consta-design-system/charts#31]
наши клиенты просят отобразить несколько графиков под одной легендой, это можно сделать с помощью 
https://g2plot.antv.vision/en/examples/plugin/multi-view#series-columns

прошу добавить поддержку такой возможности

![image](https://user-images.githubusercontent.com/37770694/147360269-ac2ffa52-c170-4798-b8a2-43e517637d3b.png)

**Comment by Lyubavskaya** [comment]
Сделали в v0.4.0 (26/01/2022)
