### ISSUE TITLE
цвет подписи оси координат для Line, Column, Dual

### ISSUE THREAD

**Issue by 4adOFF** [consta-design-system/charts#33]
По умолчанию цвет подписи для графиков Line, Column, Dual

При необходимости можно переопределить цвет при создании графика (https://g2plot.antv.vision/en/docs/api/components/axis/#title), но в случае с использованием нескольких тем это сделать проблематично да и не совсем правильно, логичнее будет выглядит цвет в соответствии с темой для данного элемента.

![тайтл1](https://user-images.githubusercontent.com/3755334/148760153-81f6e049-f1ff-4977-8772-5805998320c8.JPG)
![тайтл2](https://user-images.githubusercontent.com/3755334/148760156-2160351e-9313-4407-86e4-e094fdd72964.JPG)

**Comment by Lyubavskaya** [comment]
Исправлено в v0.4.0 (26/01/2022)
